name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - front  # Replace with the branch you want to trigger the workflow on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./client

      - name: Build React app
        run: |
          npm run build
        working-directory: ./client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
